docker network create cc_frontend && docker network create cc_backend && docker compose up --build
2016ea25ac2b4acf0092424ef49489a5dc624c63ff655bae1f994c157c72e7d5
bba2fa67778f1d190cc5f1fff178c4b8a22cd7af235538dd817c4e938a871d2a
#1 [cc_keycloak_db internal] load build definition from Dockerfile
#1 transferring dockerfile: 264B done
#1 DONE 0.0s

#2 [cc_keycloak internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.1s

#3 [cc_keycloak_db internal] load .dockerignore
#3 transferring context: 2B 0.0s done
#3 DONE 0.1s

#4 [cc_keycloak internal] load build definition from Dockerfile
#4 transferring dockerfile: 756B 0.0s done
#4 DONE 0.1s

#5 [cc_keycloak internal] load metadata for quay.io/keycloak/keycloak:latest
#5 ...

#6 [cc_keycloak_db internal] load metadata for docker.io/library/postgres:latest
#6 DONE 1.1s

#7 [cc_keycloak_db 1/4] FROM docker.io/library/postgres:latest@sha256:6b07fc4fbcf551ea4546093e90cecefc9dc60d7ea8c56a4ace704940b6d6b7a3
#7 DONE 0.0s

#8 [cc_keycloak_db internal] load build context
#8 transferring context: 412B done
#8 DONE 0.0s

#9 [cc_keycloak_db 3/4] WORKDIR /docker-entrypoint-initdb.d/
#9 CACHED

#10 [cc_keycloak_db 2/4] RUN mkdir -p docker-entrypoint-initdb.d
#10 CACHED

#11 [cc_keycloak_db 4/4] COPY init_db.sql /docker-entrypoint-initdb.d
#11 CACHED

#12 [cc_keycloak_db] exporting to image
#12 exporting layers done
#12 writing image sha256:4bdd121455fdcc10f04ec505bc0558519d6aa233150358b4e2ad2bc752c08eb4 0.0s done
#12 naming to docker.io/library/cc_keycloak_db 0.0s done
#12 DONE 0.2s

#5 [cc_keycloak internal] load metadata for quay.io/keycloak/keycloak:latest
#5 DONE 1.9s

#13 [cc_keycloak stage-1 1/2] FROM quay.io/keycloak/keycloak:latest@sha256:b8f2a453a17a244a829fdafdb08dd77f719d3622bc3987c76a81771c0913b882
#13 DONE 0.0s

#14 [cc_keycloak builder 2/4] WORKDIR /opt/keycloak
#14 CACHED

#15 [cc_keycloak builder 3/4] RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
#15 CACHED

#16 [cc_keycloak builder 4/4] RUN /opt/keycloak/bin/kc.sh build
#16 CACHED

#17 [cc_keycloak stage-1 2/2] COPY --from=builder /opt/keycloak/ /opt/keycloak/
#17 CACHED

#12 [cc_keycloak] exporting to image
#12 exporting layers done
#12 writing image sha256:8ceeed66aa79f8c9ef609274969976944ef33d1774199f3ecab5397edb59a4d6
#12 writing image sha256:8ceeed66aa79f8c9ef609274969976944ef33d1774199f3ecab5397edb59a4d6 0.0s done
#12 naming to docker.io/library/cc_keycloak 0.0s done
#12 DONE 0.2s
Attaching to cc_keycloak, cc_keycloak_db
cc_keycloak_db  | The files belonging to this database system will be owned by user "postgres".
cc_keycloak_db  | This user must also own the server process.
cc_keycloak_db  | 
cc_keycloak_db  | The database cluster will be initialized with locale "en_US.utf8".
cc_keycloak_db  | The default database encoding has accordingly been set to "UTF8".
cc_keycloak_db  | The default text search configuration will be set to "english".
cc_keycloak_db  | 
cc_keycloak_db  | Data page checksums are disabled.
cc_keycloak_db  | 
cc_keycloak_db  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
cc_keycloak_db  | creating subdirectories ... ok
cc_keycloak_db  | selecting dynamic shared memory implementation ... posix
cc_keycloak_db  | selecting default max_connections ... 100
cc_keycloak_db  | selecting default shared_buffers ... 128MB
cc_keycloak_db  | selecting default time zone ... Europe/Madrid
cc_keycloak_db  | creating configuration files ... ok
cc_keycloak_db  | running bootstrap script ... ok
cc_keycloak_db  | performing post-bootstrap initialization ... ok
cc_keycloak     | Updating the configuration and installing your custom providers, if any. Please wait.
cc_keycloak_db  | syncing data to disk ... ok
cc_keycloak_db  | 
cc_keycloak_db  | 
cc_keycloak_db  | Success. You can now start the database server using:
cc_keycloak_db  | 
cc_keycloak_db  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
cc_keycloak_db  | 
cc_keycloak_db  | initdb: warning: enabling "trust" authentication for local connections
cc_keycloak_db  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
cc_keycloak_db  | waiting for server to start....2023-01-19 00:26:11.842 CET [46] LOG:  starting PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
cc_keycloak_db  | 2023-01-19 00:26:11.844 CET [46] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
cc_keycloak_db  | 2023-01-19 00:26:11.852 CET [49] LOG:  database system was shut down at 2023-01-19 00:26:09 CET
cc_keycloak_db  | 2023-01-19 00:26:11.857 CET [46] LOG:  database system is ready to accept connections
cc_keycloak_db  |  done
cc_keycloak_db  | server started
cc_keycloak_db  | CREATE DATABASE
cc_keycloak_db  | 
cc_keycloak_db  | 
cc_keycloak_db  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init_db.sql
cc_keycloak_db  | CREATE DATABASE
cc_keycloak_db  | CREATE ROLE
cc_keycloak_db  | ALTER ROLE
cc_keycloak_db  | ALTER ROLE
cc_keycloak_db  | ALTER ROLE
cc_keycloak_db  | GRANT
cc_keycloak_db  | 
cc_keycloak_db  | 
cc_keycloak_db  | 2023-01-19 00:26:12.417 CET [46] LOG:  received fast shutdown request
cc_keycloak_db  | waiting for server to shut down....2023-01-19 00:26:12.422 CET [46] LOG:  aborting any active transactions
cc_keycloak_db  | 2023-01-19 00:26:12.434 CET [46] LOG:  background worker "logical replication launcher" (PID 52) exited with exit code 1
cc_keycloak_db  | 2023-01-19 00:26:12.436 CET [47] LOG:  shutting down
cc_keycloak_db  | 2023-01-19 00:26:12.444 CET [47] LOG:  checkpoint starting: shutdown immediate
cc_keycloak_db  | 2023-01-19 00:26:13.024 CET [47] LOG:  checkpoint complete: wrote 1842 buffers (11.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.130 s, sync=0.439 s, total=0.588 s; sync files=504, longest=0.016 s, average=0.001 s; distance=8438 kB, estimate=8438 kB
cc_keycloak_db  | 2023-01-19 00:26:13.034 CET [46] LOG:  database system is shut down
cc_keycloak_db  |  done
cc_keycloak_db  | server stopped
cc_keycloak_db  | 
cc_keycloak_db  | PostgreSQL init process complete; ready for start up.
cc_keycloak_db  | 
cc_keycloak_db  | 2023-01-19 00:26:13.184 CET [1] LOG:  starting PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
cc_keycloak_db  | 2023-01-19 00:26:13.185 CET [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
cc_keycloak_db  | 2023-01-19 00:26:13.185 CET [1] LOG:  listening on IPv6 address "::", port 5432
cc_keycloak_db  | 2023-01-19 00:26:13.189 CET [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
cc_keycloak_db  | 2023-01-19 00:26:13.193 CET [64] LOG:  database system was shut down at 2023-01-19 00:26:13 CET
cc_keycloak_db  | 2023-01-19 00:26:13.242 CET [1] LOG:  database system is ready to accept connections
cc_keycloak     | 2023-01-18 23:26:30,490 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 16207ms
cc_keycloak     | 2023-01-18 23:26:33,234 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
cc_keycloak     | 2023-01-18 23:26:35,137 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
cc_keycloak     | 2023-01-18 23:26:35,146 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
cc_keycloak     | 2023-01-18 23:26:35,147 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
cc_keycloak     | 2023-01-18 23:26:35,233 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:26:35,658 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:26:35,663 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
cc_keycloak     | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
cc_keycloak     | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
cc_keycloak     | 	at org.postgresql.Driver.makeConnection(Driver.java:434)
cc_keycloak     | 	at org.postgresql.Driver.connect(Driver.java:291)
cc_keycloak     | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
cc_keycloak     | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
cc_keycloak     | 	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
cc_keycloak     | 	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
cc_keycloak     | 	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
cc_keycloak     | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:232)
cc_keycloak     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
cc_keycloak     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
cc_keycloak     | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
cc_keycloak     | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
cc_keycloak     | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
cc_keycloak     | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
cc_keycloak     | 	at java.base/java.lang.Thread.run(Thread.java:829)
cc_keycloak     | Caused by: java.net.ConnectException: Connection refused (Connection refused)
cc_keycloak     | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
cc_keycloak     | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
cc_keycloak     | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
cc_keycloak     | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
cc_keycloak     | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
cc_keycloak     | 	at java.base/java.net.Socket.connect(Socket.java:609)
cc_keycloak     | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
cc_keycloak     | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
cc_keycloak     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
cc_keycloak     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
cc_keycloak     | 	... 17 more
cc_keycloak     | 
cc_keycloak     | 2023-01-18 23:26:36,678 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
cc_keycloak     | 2023-01-18 23:26:36,738 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
cc_keycloak     | 2023-01-18 23:26:36,772 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
cc_keycloak     | 2023-01-18 23:26:37,255 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
cc_keycloak     | 2023-01-18 23:26:38,020 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_125227, Site name: null
cc_keycloak     | 2023-01-18 23:26:38,046 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:26:38,281 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
cc_keycloak     | 2023-01-18 23:26:38,282 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
cc_keycloak     | 2023-01-18 23:26:38,283 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:26:38,283 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connection refused (Connection refused)
cc_keycloak     | 2023-01-18 23:26:38,284 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
cc_keycloak exited with code 1
cc_keycloak     | 2023-01-18 23:26:43,329 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
cc_keycloak     | 2023-01-18 23:26:45,607 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
cc_keycloak     | 2023-01-18 23:26:45,629 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
cc_keycloak     | 2023-01-18 23:26:45,629 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
cc_keycloak     | 2023-01-18 23:26:45,720 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:26:46,051 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:26:46,055 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
cc_keycloak     | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
cc_keycloak     | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
cc_keycloak     | 	at org.postgresql.Driver.makeConnection(Driver.java:434)
cc_keycloak     | 	at org.postgresql.Driver.connect(Driver.java:291)
cc_keycloak     | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
cc_keycloak     | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
cc_keycloak     | 	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
cc_keycloak     | 	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
cc_keycloak     | 	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
cc_keycloak     | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:232)
cc_keycloak     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
cc_keycloak     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
cc_keycloak     | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
cc_keycloak     | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
cc_keycloak     | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
cc_keycloak     | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
cc_keycloak     | 	at java.base/java.lang.Thread.run(Thread.java:829)
cc_keycloak     | Caused by: java.net.ConnectException: Connection refused (Connection refused)
cc_keycloak     | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
cc_keycloak     | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
cc_keycloak     | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
cc_keycloak     | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
cc_keycloak     | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
cc_keycloak     | 	at java.base/java.net.Socket.connect(Socket.java:609)
cc_keycloak     | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
cc_keycloak     | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
cc_keycloak     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
cc_keycloak     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
cc_keycloak     | 	... 17 more
cc_keycloak     | 
cc_keycloak     | 2023-01-18 23:26:47,200 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
cc_keycloak     | 2023-01-18 23:26:47,231 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
cc_keycloak     | 2023-01-18 23:26:47,273 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
cc_keycloak     | 2023-01-18 23:26:47,658 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
cc_keycloak     | 2023-01-18 23:26:48,327 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_651748, Site name: null
cc_keycloak     | 2023-01-18 23:26:48,350 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:26:48,626 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
cc_keycloak     | 2023-01-18 23:26:48,627 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
cc_keycloak     | 2023-01-18 23:26:48,628 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:26:48,628 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connection refused (Connection refused)
cc_keycloak     | 2023-01-18 23:26:48,629 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
cc_keycloak exited with code 1
cc_keycloak     | 2023-01-18 23:26:55,645 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
cc_keycloak     | 2023-01-18 23:26:58,576 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
cc_keycloak     | 2023-01-18 23:26:58,598 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
cc_keycloak     | 2023-01-18 23:26:58,599 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
cc_keycloak     | 2023-01-18 23:26:58,697 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:26:59,068 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:26:59,072 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
cc_keycloak     | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
cc_keycloak     | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
cc_keycloak     | 	at org.postgresql.Driver.makeConnection(Driver.java:434)
cc_keycloak     | 	at org.postgresql.Driver.connect(Driver.java:291)
cc_keycloak     | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
cc_keycloak     | 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
cc_keycloak     | 	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
cc_keycloak     | 	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
cc_keycloak     | 	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
cc_keycloak     | 	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:232)
cc_keycloak     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
cc_keycloak     | 	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
cc_keycloak     | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
cc_keycloak     | 	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
cc_keycloak     | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
cc_keycloak     | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
cc_keycloak     | 	at java.base/java.lang.Thread.run(Thread.java:829)
cc_keycloak     | Caused by: java.net.ConnectException: Connection refused (Connection refused)
cc_keycloak     | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
cc_keycloak     | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
cc_keycloak     | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
cc_keycloak     | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
cc_keycloak     | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
cc_keycloak     | 	at java.base/java.net.Socket.connect(Socket.java:609)
cc_keycloak     | 	at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
cc_keycloak     | 	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
cc_keycloak     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
cc_keycloak     | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
cc_keycloak     | 	... 17 more
cc_keycloak     | 
cc_keycloak     | 2023-01-18 23:27:01,279 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
cc_keycloak     | 2023-01-18 23:27:01,315 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
cc_keycloak     | 2023-01-18 23:27:01,418 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
cc_keycloak     | 2023-01-18 23:27:02,053 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.10.Final
cc_keycloak     | 2023-01-18 23:27:03,402 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_65570, Site name: null
cc_keycloak     | 2023-01-18 23:27:03,429 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:27:03,660 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
cc_keycloak     | 2023-01-18 23:27:03,661 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
cc_keycloak     | 2023-01-18 23:27:03,662 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
cc_keycloak     | 2023-01-18 23:27:03,662 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Connection refused (Connection refused)
cc_keycloak     | 2023-01-18 23:27:03,663 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
cc_keycloak exited with code 1
cc_keycloak     | 2023-01-18 23:27:09,653 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
cc_keycloak     | 2023-01-18 23:27:12,327 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
cc_keycloak     | 2023-01-18 23:27:12,348 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
cc_keycloak     | 2023-01-18 23:27:12,349 WARN  [io.agroal.pool] (main) Datasource '<default>': Ignoring property 'URL': null
cc_keycloak     | 2023-01-18 23:27:12,447 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Gracefully stopping... (press Ctrl+C again to force)
